version: "3.8"

services:
  app:
    container_name: purrfect-creations-web
    image: purrfect-creations-web
    build:
      context: .
      target: development
    volumes:
      - ./src:/purrfect-creations/web/src
    ports:
      - 3000:3000
